#!/bin/bash
# run workstation command with "rad_mat" which really just sets pipeline startup
#
# if you want to email output see email example below
if [ -z $1 ];then
    echo "please specify runno!";
    exit;
fi;
args="";
for arg in $@; do 
    if [ ! -z "$args" ];then
	args="$args,'$arg'";
    else
	args="'$arg'";
    fi;
done

cd ${WKS_SHARED}/pipeline_utilities;
#echo /usr/local/bin/matlab -nodesktop -noFigureWindows -nojvm -r "status_CS_recon($args);exit";exit;
/usr/local/bin/matlab -nodesktop -noFigureWindows -r "status_CS_recon($args);exit"

# example cron job to send mail to some user.
#min     hour          day     month weekday
#52      5,11,16,21      *       *       *       source $HOME/.bashrc; status_CS_recon S67962 2>&1 | mail -s "status_CS_recon S67962" $USER@duke.edu

# example cronjob to send mail to user running job, and email any images generated by the status reporter.
# 53	5,11,16,21	*	*	*	source $HOME/.bashrc; t_run="S67962";s_file=$HOME/CS_recon_${t_run}.status;status_CS_recon $t_run Write 2>&1 > $s_file; attachments=$(grep -- '->' ${s_file} |awk '{print $2}'); cat $s_file| mail -s "status_CS_recon $t_run" $(for at in  "$attachments" ; do if [ ! -z "$at" ]; then echo -n " -a $at";fi;done) $USER@duke.edu







