%compile me
function compile_command_gui_test
%exec_env_var='';%optional shell env var to be cleared.
include_files = {'agilent2glusterspaceCS.m' ...
    'load_fid_hdrCS.m' ... 
    'readprocparCS.m' ...
    'gui_info_collect.m' ...    
    'puller_glusterspaceCS.m'
    };%optional, but required if using exec_env_var, can be empty.
compile_command__allpurpose('gui_test_exec.m',include_files);%,exec_env_var);
